### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by pipinoloco** [austinyearlykim/wolf#10]
This mistakes happens randomly 
![wolferror1](https://user-images.githubusercontent.com/29177517/35659489-519cdd2c-06e5-11e8-9332-d982dae923c4.JPG)

**Comment by austinyearlykim** [comment]
Binance is saying that one of WOLF's requests to check the order status is taking longer than the default 5 seconds.  I'll go ahead and add a parameter to double the accepted time, or `recvWindow`.  That should at least make the error appear less often.  

I'm hesitant to increase it more than 10 because if it takes longer than that I would rather have the next request take precedence anyway.

I'll close this issue with the commit hash when I've fixed this.  Thanks @pipinoloco

**Comment by austinyearlykim** [comment]
After reading the Binance API documentation, which says that trade bots should use 5 seconds or fewer, I've decided to just exit the function loop if the status check is deemed invalid and just wait for the next check.  

https://github.com/austinyearlykim/wolf/commit/ebab0db43f8c29915502892b262910b3f2dd94b1
