### ISSUE TITLE
output spamming.

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#32]
Is possible to slow down the output or only have it only out put when it successfully finishes a trade. Because I'm getting this every 3 seconds or so:

Consumed queue. Orders in queue: 1
Consuming queue... Orders in queue: 1
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 1
Consuming queue... Orders in queue: 1
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 1
Consuming queue... Orders in queue: 1
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 1
Consuming queue... Orders in queue: 1
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 1
Consuming queue... Orders in queue: 1
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 1
Consuming queue... Orders in queue: 1

and it keeps going until it makes a successful trade.

would be nice if it could just output this:
PURCHASED: 330.00000000TRXBTC @  0.00000910
WAITING ON SELL @ 0.00000930 

or something like that, just a thought.
P.S. I'm loving the bot, can't wait to see the next set of updates.

**Comment by austinyearlykim** [comment]
This has been a common request.  And I already have plans on ideas on how to make this less spammy.  Stay tuned for v3.5.0 it's going to be a good one.  Thanks @BatmanPDX

**Comment by pitxels** [comment]
Yes it can be spammy, but you actually want to see the the bot is online and is sending this ping. Otherwise you won't notice is disconnected and you left a trade unattended. 

One problem I see with this current log is that sometimes you don't know if is frozen or showing a new status, because all the text is the same. So maybe a timestamp can help.

Like everything in software some users want the feature and some other don't. So maybe adding a variable for how often this logs show up can solve the problem.

**Comment by austinyearlykim** [comment]
https://github.com/austinyearlykim/wolf/pull/62

Done :)
