### ISSUE TITLE
is it possible to execute a negative trade?

### ISSUE THREAD

**Issue by sasasavic82** [austinyearlykim/wolf#4]
I've been testing it out with 0.0045 BTC (About AUD$50), but each time I refresh my total, it's being decreased - i.e.:

0.004543333
0.004541348
0.004535346

I don't think it's made a profitable trade not even once. Can it make a negative trade?

**Comment by austinyearlykim** [comment]
Hi @sasasavic82, WOLF actually *can't* execute a negative trade.  It can however purchase an entity and not be able to sell it (you can always just sell it yourself as well!).  

What could be happening is that you're buying ETH with BTC and WOLF is waiting to execute a trade at a price that is profitable.  If it fails to execute in a number of intervals then it will keep your sell order open and move on to another purchase which it will then try to sell at a profitable price at a smaller margin.

So while it is NOT possible to execute a negative trade, it is possible that you are "stuck" with the coin that you are trying to scalp with decreasing your btc total

Please let me know if you need more clarification on anything else; WOLF is a work in progress and will only get smarter from here;  I do need to refactor the code a bit to make it more pull request friendly and modularized; but I was so inspired to make v1.0.0 I wanted to get the first working version up asap.

**Comment by sasasavic82** [comment]
perhaps a better option would be to cancel order all together? ... are there order cancellation fees? from memory, there aren't.

you should be able to cancel by orderId?

thoughts? ... if that makes sense

**Comment by austinyearlykim** [comment]
Yes!  I was planning to put in logic where on process.exit(0) WOLF will look at your open orders that WOLF created, and cancel those for you.  This cancel can also happen on reset();

Sit tight for v.1.1.0 !

**Comment by sasasavic82** [comment]
hey bud, I'm still a little baffled - I was tracking the value of my BTC as the bot was making trades:

> 0.00463384
> 0.00462822
> 0.00462599
> 0.00462601
> 0.00462246
> 0.00461396
> 0.00461081
> 0.00460640
> 0.00460886
> 0.00460652
> 0.00461401
> 0.00460714

Also, in this statement:

`        temp.optimalBuyPrice = (Number(depth.bids[0].price) + 0.00000100).toFixed(8);
          temp.optimalAskPrice = (Number(depth.asks[0].price) - 0.00000100).toFixed(8);`

Should you not be buying low, and asking higher? What's the logic behind optimal*

Thanks :)

**Comment by CallMeAldy** [comment]
@sasasavic82 Are you using BNB to pay the fees?

**Comment by sasasavic82** [comment]
Nope, I switched it off. Just the standard 0.001 (0.1%) fee.

**Comment by sasasavic82** [comment]
Profitable trades are a hard problem to solve... check https://github.com/DeviaVir/zenbot 

there's significant amount of work done and dedicated to it,yet it's not profitable.

**Comment by CallMeAldy** [comment]
I've been using BNB to pay the fees and have set the profit percentage to 25.5. You might want to try that.

**Comment by CallMeAldy** [comment]
Yes, you need to purchase some BNB and turn on the BNB settings. I've seen it converting within a few minutes and my BTC balance is increasing too.

**Comment by sasasavic82** [comment]
How long does it take the order to reach a 25.5% profit?

**Comment by austinyearlykim** [comment]
@sasasavic82 my dude!

Are we both aware that BTC price value fluctuates naturally?  Not only because of the bot, but because the price is moving because the market is moving?  So it seems only natural that your btc value goes up AND down.  To confirm whether or not you're currently profiting (which you should be) is to go to each BUY and SELL and compare the prices at which each are executed at.  You can find this at:   https://www.binance.com/userCenter/orderHistory.html

Your question about the optimal prices...I can see the confusion here but let me help try to clarify!
temp.optimalBuyPrice = (Number(depth.bids[0].price) + 0.00000100).toFixed(8); temp.optimalAskPrice = (Number(depth.asks[0].price) - 0.00000100).toFixed(8);

WOLF only does limit orders never market orders.  Buying slighter higher and selling at slighter lower will "pseudo-guarantee" order execution, because WOLF is then scalping the order book with LIMIT ORDERS by the lowest margin which is 100 satoshi!  However, WOLF still guarantees a profit by only selling if the optimal ask price is greater than (PROFIT_PERCENTAGE*optimalBuyPrice) + optimalBuyPrice as seen here:
https://github.com/austinyearlykim/wolf/blob/master/index.js#L79

I'm excited to release the next version of WOLF.  Naming conventions and code structure changes are going to feel so good.. 😸

**Comment by sasasavic82** [comment]
Noted!.. thoughts on 25.5% profit setting? :)

**Comment by sasasavic82** [comment]
Also, what is the ultimate goal? accumulating BTC?

**Comment by austinyearlykim** [comment]
@sasasavic82 Yes!  The goal is to accumulate the currency of choice.  Which in the default .env, is BTC, because ETHBTC trading pair means you're scalping ETH to accumulate more bitcoin.
